### ISSUE TITLE
numpy版本问题

### ISSUE THREAD

**Issue by Smawexi** [Gerapy/GerapyAutoExtractor#21]
从1.18版本开始，numpy正式淘汰了numpy.testing.decorators这一系列模块名（注意：只是淘汰了模块名，他们实质上包含的内容还在），并且贴心地告诉用户，要用umpy.testing.decorators里面的功能（命名空间），只需要import numpy.testing 就够了，自当前版本开始的testing自动会包含原有的testing.decorations等子模块
作者可以更新一下相关的包嘛？，我用的numpy版本是1.19.5，出了点问题，如下：
D:\fsy\Anaconda\python.exe D:/python_study/IntelligentAnalysis/extract.py
Traceback (most recent call last):
  File "D:/python_study/IntelligentAnalysis/extract.py", line 1, in <module>
    from gerapy_auto_extractor import extract_detail
  File "D:\fsy\Anaconda\lib\site-packages\gerapy_auto_extractor\__init__.py", line 4, in <module>
    from gerapy_auto_extractor.classifiers.list import is_list, probability_of_list
  File "D:\fsy\Anaconda\lib\site-packages\gerapy_auto_extractor\classifiers\list.py", line 6, in <module>
    from sklearn.metrics import classification_report
  File "D:\fsy\Anaconda\lib\site-packages\sklearn\__init__.py", line 82, in <module>
    from .base import clone
  File "D:\fsy\Anaconda\lib\site-packages\sklearn\base.py", line 17, in <module>
    from .utils import _IS_32BIT
  File "D:\fsy\Anaconda\lib\site-packages\sklearn\utils\__init__.py", line 23, in <module>
    from .class_weight import compute_class_weight, compute_sample_weight
  File "D:\fsy\Anaconda\lib\site-packages\sklearn\utils\class_weight.py", line 7, in <module>
    from .validation import _deprecate_positional_args
  File "D:\fsy\Anaconda\lib\site-packages\sklearn\utils\validation.py", line 26, in <module>
    from .fixes import _object_dtype_isnan, parse_version
  File "D:\fsy\Anaconda\lib\site-packages\sklearn\utils\fixes.py", line 20, in <module>
    import scipy.stats
  File "D:\fsy\Anaconda\lib\site-packages\scipy\stats\__init__.py", line 345, in <module>
    from .morestats import *
  File "D:\fsy\Anaconda\lib\site-packages\scipy\stats\morestats.py", line 12, in <module>
    from numpy.testing.decorators import setastest
ModuleNotFoundError: No module named 'numpy.testing.decorators'

**Comment by Germey** [comment]
多谢，我会 fix 下哈～
