### ISSUE TITLE
max() arg is an empty sequence

### ISSUE THREAD

**Issue by perrornet** [Gerapy/GerapyAutoExtractor#7]
**Describe the bug**
使用is_list函数判断内容是否属于列表页面,得到true后, 调用extract_list函数,发生了错误:
`ValueError: max() arg is an empty sequence`

**To Reproduce**
1. Content of your page html: https://www.qukuaiwang.com.cn/Index/ku_detail/kid/4812.html
2. Contnet of Your code:
```python
import requests
from gerapy_auto_extractor import extract_list, extract_detail, is_detail, is_list

content = requests.get("https://www.qukuaiwang.com.cn/Index/ku_detail/kid/4812.html").text
if is_list(content):
    print(extract_list(content))
```
3. See error
```
Traceback (most recent call last):
  File "C:/Users/qinya/PycharmProjects/x7Nlp/1.py", line 7, in <module>
    print(extract_list(content))
  File "C:\Users\qinya\Anaconda3\envs\synonyms\lib\site-packages\gerapy_auto_extractor\extractors\list.py", line 246, in extract_list
    return list_extractor.extract(html, **kwargs)
  File "C:\Users\qinya\Anaconda3\envs\synonyms\lib\site-packages\gerapy_auto_extractor\extractors\base.py", line 45, in extract
    return self.process(element)
  File "C:\Users\qinya\Anaconda3\envs\synonyms\lib\site-packages\gerapy_auto_extractor\extractors\list.py", line 234, in process
    return self._extract_cluster(best_cluster)
  File "C:\Users\qinya\Anaconda3\envs\synonyms\lib\site-packages\gerapy_auto_extractor\extractors\list.py", line 187, in _extract_cluster
    best_path = max(probabilities_of_title_avg.items(), key=operator.itemgetter(1))[0]
ValueError: max() arg is an empty sequence
```

**Expected behavior**
该页面应该属于内容页面,但是使用is_list却返回true,调用extract_list函数应该返回空

**Screenshots**
页面截图:
![image](https://user-images.githubusercontent.com/23651751/88804008-e221ce80-d1df-11ea-9e2b-db929cf50a07.png)

**Desktop (please complete the following information):**
 - OS: win10
 - Python 3.7
 - Package Version :0.1.0

**Comment by Germey** [comment]
我先临时修复了这个 Bug，发布了 0.1.1 版本。

现在如果这个页面 extract_list 不会报错了，但是提取不到有效 list。

判断 list 的这个的确是问题，我后面统一优化。

谢谢。
